CLASS zbp_i_online_shop_047 DEFINITION PUBLIC ABSTRACT FINAL FOR
BEHAVIOR OF zi_online_shop_047.
  PUBLIC SECTION.
    CLASS-DATA cv_pr_mapped TYPE RESPONSE FOR MAPPED
    i_purchaserequisitiontp.
    CLASS-DATA cv_po_mapped TYPE RESPONSE FOR MAPPED I_PurchaseOrderTP_2.
ENDCLASS.

CLASS zbp_i_online_shop_047 IMPLEMENTATION.
ENDCLASS.
